WORLD = {
    "id": "maple_street",
    "name": "Maple Street",
    "theme": "cozy modern suburb",
    "diorama": "assets/worlds/maple_street.png",
    "palette": {
        "bg": "#0b0f1a",
        "grass": "#1a4a2a",
        "road": "#1e2235",
        "house": "#c45b5b",
        "park": "#0a3a2a",
        "tree": "#0a2a1a",
        "sky": "#0a0f1a",
        "tint_day": "#fff3d6",
        "tint_night": "#1a2342",
    },
    "hotspots": {
        "marta_home": [17, 63],
        "cafe": [72, 58],
        "park": [58, 50],
        "square": [48, 73],
        "jay_home": [89, 87],
        "school": [37, 56],
        "nia_clinic": [13, 81],
        "priya_office": [82, 78],
    },
    "scenery": {
        "buildings": [
            {"left": 5,  "top": 40, "w": 15, "h": 15, "front": "#3a2b4d", "roof": "#ff5fa2", "side": "#241a33", "label": "🕰️"},
            {"left": 27, "top": 33, "w": 20, "h": 14, "front": "#23314f", "roof": "#38e8ff", "side": "#16213a", "label": "🏫"},
            {"left": 63, "top": 36, "w": 17, "h": 14, "front": "#4a3b2b", "roof": "#ffd76a", "side": "#33291d", "label": "☕"},
            {"left": 3,  "top": 61, "w": 14, "h": 14, "front": "#1f3d3a", "roof": "#7CFFB2", "side": "#142826", "label": "🚑"},
            {"left": 71, "top": 53, "w": 16, "h": 17, "front": "#2c2b4d", "roof": "#9b6bff", "side": "#1d1c33", "label": "🏢"},
            {"left": 82, "top": 69, "w": 14, "h": 12, "front": "#3a2030", "roof": "#ff8a5f", "side": "#281622", "label": "🏪"},
        ],
        "roads": [
            {"left": -5, "top": 66, "w": 120, "h": 9,  "rot": -8},
            {"left": 40, "top": 30, "w": 9,  "h": 70, "rot": 6},
        ],
        "trees": [
            {"left": 21, "top": 52, "s": 1.0},
            {"left": 52, "top": 46, "s": 0.8},
            {"left": 62, "top": 66, "s": 1.1},
            {"left": 33, "top": 80, "s": 0.9},
            {"left": 94, "top": 52, "s": 0.8},
        ],
        "props": [
            {"left": 49, "top": 64, "emoji": "⛲"},
            {"left": 30, "top": 67, "emoji": "🪧"},
        ],
    },
    "cast": [
        {
            "name": "Marta Voss",
            "age": 68,
            "job": "retired watchmaker",
            "traits": ["blunt", "observant", "nostalgic"],
            "backstory": "She ran the neighborhood clock shop for four decades and still notices every tiny change on the street.",
            "relationships": {
                "Jay Park": "rival",
                "Nia Okafor": "friend",
                "Luca Bell": "family",
                "Priya Raman": "friend",
            },
            "voice_description": "(a grumpy elderly woman, deep measured low-pitched voice)",
            "model": "nvidia/Nemotron-Mini-4B-Instruct",
            "emoji": "🧓",
            "home": "marta_home",
            "catchphrase_hint": "always compares things to the past",
        },
        {
            "name": "Jay Park",
            "age": 24,
            "job": "food delivery cyclist",
            "traits": ["restless", "funny", "impulsive"],
            "backstory": "He knows every shortcut in the district and treats ordinary afternoons like they might become legends.",
            "relationships": {
                "Marta Voss": "rival",
                "Nia Okafor": "crush",
                "Luca Bell": "friend",
                "Priya Raman": "friend",
            },
            "voice_description": "(an energetic young man, quick bright mid-pitched voice)",
            "model": "nvidia/Nemotron-Mini-4B-Instruct",
            "emoji": "🚴",
            "home": "jay_home",
            "catchphrase_hint": "turns everything into an adventure",
        },
        {
            "name": "Nia Okafor",
            "age": 35,
            "job": "paramedic",
            "traits": ["calm", "protective", "dry-witted"],
            "backstory": "After years on emergency shifts, she reads chaos quickly and trusts people more than they expect.",
            "relationships": {
                "Marta Voss": "friend",
                "Jay Park": "crush",
                "Luca Bell": "friend",
                "Priya Raman": "family",
            },
            "voice_description": "(a steady adult woman, warm confident medium-low voice)",
            "model": "nvidia/Nemotron-Mini-4B-Instruct",
            "emoji": "🚑",
            "home": "nia_clinic",
            "catchphrase_hint": "downplays danger but always steps up",
        },
        {
            "name": "Luca Bell",
            "age": 15,
            "job": "student and arcade regular",
            "traits": ["curious", "dramatic", "inventive"],
            "backstory": "He documents neighborhood rumors in a battered notebook and is convinced something world-changing will happen here first.",
            "relationships": {
                "Marta Voss": "family",
                "Jay Park": "friend",
                "Nia Okafor": "friend",
                "Priya Raman": "rival",
            },
            "voice_description": "(a teenage boy, eager expressive slightly high-pitched voice)",
            "model": "nvidia/Nemotron-Mini-4B-Instruct",
            "emoji": "🧒",
            "home": "school",
            "catchphrase_hint": "treats everything like breaking news",
        },
        {
            "name": "Priya Raman",
            "age": 42,
            "job": "city planner",
            "traits": ["organized", "skeptical", "secretly romantic"],
            "backstory": "She came to fix the block's chronic little problems and keeps getting pulled into everyone else's dramas.",
            "relationships": {
                "Marta Voss": "friend",
                "Jay Park": "friend",
                "Nia Okafor": "family",
                "Luca Bell": "rival",
            },
            "voice_description": "(a precise middle-aged woman, crisp thoughtful medium voice)",
            "model": "nvidia/Nemotron-Mini-4B-Instruct",
            "emoji": "👩‍💼",
            "home": "priya_office",
            "catchphrase_hint": "tries to stay logical but feelings leak through",
        },
    ],
    "board": {
        # A real residential street: a suburban grid of homes with a small high street,
        # a school, a clinic and a park. Deliberately NOT the same shape as the other worlds.
        "cols": 22,
        "rows": 18,
        "ambient": 6,
        "roads": {"cols": [5, 11, 17], "rows": [6, 13]},
        "plaza": [[12, 9], [13, 9], [12, 10], [13, 10]],
        "plaza_center": [12.5, 9.5],
        "buildings": [
            # homes — pitched-roof houses in warm, lived-in colours (most of a neighborhood is houses)
            {"gx": 1,  "gy": 1,  "w": 2, "d": 2, "h": 24, "kind": "house", "wall": "#caa074", "roof": "#8a3b2e", "label": "MARTA"},
            {"gx": 8,  "gy": 1,  "w": 2, "d": 2, "h": 24, "kind": "house", "wall": "#b6c081", "roof": "#4a6b32", "label": "THE PARKS"},
            {"gx": 19, "gy": 1,  "w": 2, "d": 2, "h": 26, "kind": "house", "wall": "#b79ec0", "roof": "#5a3b6b", "label": "RAMAN"},
            {"gx": 1,  "gy": 15, "w": 2, "d": 2, "h": 24, "kind": "house", "wall": "#c79a78", "roof": "#7a4a2e", "label": "No. 12"},
            {"gx": 15, "gy": 15, "w": 2, "d": 2, "h": 24, "kind": "house", "wall": "#9ab0c0", "roof": "#3b5a6b", "label": "No. 9"},
            {"gx": 19, "gy": 9,  "w": 2, "d": 2, "h": 24, "kind": "house", "wall": "#c0a86a", "roof": "#6b5a2e", "label": "No. 7"},
            # the little high street — a café and a corner store with real storefronts
            {"gx": 14, "gy": 1,  "w": 2, "d": 2, "h": 30, "kind": "shop",  "wall": "#8a6f3f", "roof": "#ff8a5f", "label": "CAFÉ"},
            {"gx": 1,  "gy": 8,  "w": 2, "d": 2, "h": 28, "kind": "shop",  "wall": "#6f5a8a", "roof": "#38e8ff", "label": "CORNER STORE"},
            # civic — a small school and a clinic
            {"gx": 8,  "gy": 15, "w": 3, "d": 2, "h": 34, "kind": "block", "wall": "#6a6f8a", "roof": "#ffd76a", "label": "SCHOOL"},
            {"gx": 19, "gy": 15, "w": 2, "d": 2, "h": 30, "kind": "block", "wall": "#4f8576", "roof": "#7CFFB2", "label": "CLINIC"},
        ],
        "trees": [
            [9, 11], [10, 12], [7, 4], [16, 4], [4, 10], [20, 12], [7, 16], [12, 16], [18, 6], [6, 7],
        ],
        "props": [
            {"type": "fountain", "gx": 12, "gy": 12},
            {"type": "pond", "gx": 15, "gy": 11, "w": 2, "d": 2},
            {"type": "bench", "gx": 10, "gy": 11},
            {"type": "bench", "gx": 14, "gy": 12},
            # café seating on the high street
            {"type": "table", "gx": 13, "gy": 3},
            {"type": "table", "gx": 16, "gy": 3},
            # corner-store produce stall
            {"type": "stall", "gx": 3, "gy": 9, "color": "#caa23f"},
            # greenery + lamps to make it feel lived-in
            {"type": "planter", "gx": 7, "gy": 12},
            {"type": "planter", "gx": 12, "gy": 7},
            {"type": "lamp", "gx": 11, "gy": 8},
            {"type": "lamp", "gx": 14, "gy": 8},
            {"type": "lamp", "gx": 5, "gy": 12},
        ],
        "hotspots_tile": {
            "marta_home": [3, 2],
            "jay_home": [8, 3],
            "priya_office": [18, 2],
            "school": [10, 14],
            "nia_clinic": [18, 15],
            "cafe": [14, 4],
            "shop": [3, 8],
            "park": [10, 11],
            "fountain": [11, 12],
            "square": [13, 10],
        },
        # where each character goes (and what they do) when an event hits — spread out,
        # in-character, so the street reads like a real place reacting, not a mob.
        "activities": {
            "Marta Voss":  {"tile": [10, 11], "label": "🪑 watches from the park bench"},
            "Jay Park":    {"tile": [14, 4],  "label": "🚴 races to the café", "vehicle": "bike"},
            "Nia Okafor":  {"tile": [18, 15], "label": "🚑 heads to the clinic"},
            "Luca Bell":   {"tile": [11, 12], "label": "🔎 investigates the fountain"},
            "Priya Raman": {"tile": [18, 2],  "label": "🏠 hurries home to plan"},
        },
    },
    "scenarios": [
        {
            "id": "school_closing",
            "title": "The school will be closed by the city",
            "event": "The city announces Maple Street Elementary will be shut down at the end of the semester due to budget cuts.",
            "focus": "How do different generations react to losing a community institution?",
        },
        {
            "id": "new_neighbor",
            "title": "A new family moves in next door",
            "event": "A young family with two kids moves into the empty house on Maple Street. They seem nice but awfully quiet.",
            "focus": "How does the neighborhood welcome (or distrust) newcomers?",
        },
        {
            "id": "park_renovation",
            "title": "The park gets a makeover",
            "event": "The city approves a full renovation of the tiny park on Maple Street. Construction starts Monday.",
            "focus": "Who benefits from change and who loses something familiar?",
        },
        {
            "id": "power_outage",
            "title": "A summer power outage hits the block",
            "event": "A heatwave knocks out power to the entire block for an estimated six hours. No AC, no lights, no screens.",
            "focus": "How do people cope when their routines are stripped away?",
        },
    ],
    "events": [
        "A mysterious glowing object lands in the park",
        "The power goes out across the entire neighborhood",
        "A stray cat starts following people around town",
        "Someone paints a giant mural on the side of the corner store",
        "A food truck rolls in and parks in the middle of the square",
        "The old clock tower starts chiming at random hours",
        "A thunderstorm knocks down the biggest tree on Maple Street",
        "Someone leaves a box of kittens on the church doorstep",
        "The neighborhood gets its own Wikipedia page overnight",
        "A film crew shows up to shoot a commercial on the block",
    ],
}
