_M = "nvidia/Nemotron-Mini-4B-Instruct"

_TREES = [[7, 8], [12, 8], [7, 11], [12, 11], [8, 7], [11, 12], [6, 10], [13, 9],
          [3, 4], [17, 4], [3, 12], [18, 12], [6, 17], [13, 6], [18, 18], [2, 19]]

WORLD = {
    "id": "old_town",
    "name": "Old Town Market",
    "theme": "sun-warmed historic bazaar",
    "palette": {"bg": "#1a1208", "grass": "#5a4a22", "road": "#6e5630"},
    "board": {
        "cols": 20, "rows": 20,
        "roads": {"cols": [5, 14], "rows": [5, 14]},
        "plaza": [[9, 9], [10, 9], [9, 10], [10, 10]],
        "plaza_center": [9.5, 9.5],
        "buildings": [
            {"gx": 1,  "gy": 1,  "w": 2, "d": 2, "h": 116, "kind": "tower", "wall": "#9c7b4a", "roof": "#ffd76a", "label": "BELL TOWER"},
            {"gx": 8,  "gy": 1,  "w": 4, "d": 2, "h": 52,  "kind": "block", "wall": "#a85f3f", "roof": "#ff8a5f", "label": "SPICE HALL"},
            {"gx": 16, "gy": 1,  "w": 2, "d": 2, "h": 60,  "kind": "dome",  "wall": "#7a5aa0", "roof": "#9b6bff", "label": "TEA HOUSE"},
            {"gx": 1,  "gy": 8,  "w": 2, "d": 3, "h": 50,  "kind": "block", "wall": "#5f8a5a", "roof": "#7CFFB2", "label": "FLOWER STALL"},
            {"gx": 16, "gy": 7,  "w": 2, "d": 3, "h": 54,  "kind": "glass", "wall": "#3f7a8a", "roof": "#38e8ff", "label": "FISH MARKET"},
            {"gx": 1,  "gy": 16, "w": 3, "d": 2, "h": 56,  "kind": "block", "wall": "#a8895b", "roof": "#ffd76a", "label": "BAKERY"},
            {"gx": 8,  "gy": 16, "w": 4, "d": 2, "h": 58,  "kind": "dome",  "wall": "#8a5a3f", "roof": "#ff8a5f", "label": "GUILD HALL"},
            {"gx": 16, "gy": 16, "w": 2, "d": 2, "h": 52,  "kind": "block", "wall": "#9c5b5b", "roof": "#ff5fa2", "label": "INN"},
        ],
        "trees": _TREES,
        "props": [
            {"type": "fountain", "gx": 9.5, "gy": 9.5},
            {"type": "pond", "gx": 11, "gy": 7, "w": 2, "d": 2},
            {"type": "patio", "gx": 15, "gy": 9},
            {"type": "bench", "gx": 7, "gy": 10},
            {"type": "lamp", "gx": 5, "gy": 9},
            {"type": "lamp", "gx": 14, "gy": 10},
        ],
        "hotspots_tile": {
            "bell": [3, 2], "spice": [9, 3], "tea": [16, 3], "flowers": [3, 9],
            "fish": [15, 8], "bakery": [4, 16], "guild": [10, 15], "inn": [15, 16],
            "park": [8, 9], "square": [10, 11],
        },
        "activities": {
            "Halim Aziz":   {"tile": [9, 3],  "label": "🧂 minds the spice hall"},
            "Sofia Marsh":  {"tile": [3, 9],  "label": "💐 to the flower stall"},
            "Chen Wei":     {"tile": [16, 3], "label": "🍵 returns to the tea house"},
            "Tomas Reyes":  {"tile": [9, 11], "label": "🎸 plays by the fountain"},
            "Amara Diallo": {"tile": [15, 8], "label": "🐟 back to the fish market", "vehicle": "bike"},
        },
    },
    "cast": [
        {"name": "Halim Aziz", "age": 60, "job": "spice merchant",
         "traits": ["shrewd", "warm", "long-winded"],
         "backstory": "Third generation at the same stall; knows every family's history and the price of everything.",
         "relationships": {"Sofia Marsh": "friend", "Chen Wei": "old-friend", "Tomas Reyes": "fond-of", "Amara Diallo": "rival"},
         "voice_description": "(a warm older man, rich unhurried voice)", "model": _M,
         "emoji": "🧔", "home": "spice", "catchphrase_hint": "turns everything into a story and a bargain"},
        {"name": "Sofia Marsh", "age": 27, "job": "flower seller",
         "traits": ["romantic", "chatty", "soft-hearted"],
         "backstory": "Believes the right flower can mend any quarrel; knows all the market gossip.",
         "relationships": {"Halim Aziz": "friend", "Chen Wei": "respect", "Tomas Reyes": "crush", "Amara Diallo": "friend"},
         "voice_description": "(a cheerful young woman, light melodic voice)", "model": _M,
         "emoji": "👩", "home": "flowers", "catchphrase_hint": "reads feelings into everything"},
        {"name": "Chen Wei", "age": 55, "job": "tea house owner",
         "traits": ["calm", "wise", "dryly funny"],
         "backstory": "Pours tea and patience in equal measure; the market comes to him to think out loud.",
         "relationships": {"Halim Aziz": "old-friend", "Sofia Marsh": "fond-of", "Tomas Reyes": "mentor", "Amara Diallo": "friend"},
         "voice_description": "(a serene older man, slow measured voice)", "model": _M,
         "emoji": "🧓", "home": "tea", "catchphrase_hint": "answers with a calm question"},
        {"name": "Tomas Reyes", "age": 22, "job": "street musician",
         "traits": ["free-spirited", "impulsive", "generous"],
         "backstory": "Plays for coins and the joy of it; turns the day's mood into a song before anyone notices.",
         "relationships": {"Halim Aziz": "fond-of", "Sofia Marsh": "crush", "Chen Wei": "student", "Amara Diallo": "friend"},
         "voice_description": "(a lively young man, bright musical voice)", "model": _M,
         "emoji": "🧑‍🎤", "home": "guild", "catchphrase_hint": "responds like he's writing a song"},
        {"name": "Amara Diallo", "age": 40, "job": "fishmonger",
         "traits": ["loud", "big-hearted", "no-nonsense"],
         "backstory": "Up before dawn, sharp as her knives; defends the market and her friends fiercely.",
         "relationships": {"Halim Aziz": "rival", "Sofia Marsh": "friend", "Chen Wei": "friend", "Tomas Reyes": "friend"},
         "voice_description": "(a bold adult woman, loud hearty voice)", "model": _M,
         "emoji": "👩‍🦱", "home": "fish", "catchphrase_hint": "says the blunt truth nobody else will"},
    ],
    "scenarios": [
        {"id": "rent_hike", "title": "The market rents are doubling",
         "event": "The city announces that every market stall's rent will double starting next month.",
         "focus": "How do people respond when a shared livelihood is suddenly threatened?"},
        {"id": "festival", "title": "A surprise festival is announced",
         "event": "The mayor declares a city festival this weekend and the market is chosen as the main venue.",
         "focus": "Who sees opportunity, who sees disruption, and why?"},
        {"id": "lost_child", "title": "A lost child is found wandering",
         "event": "A small child is found wandering the market alone, crying, with no parent in sight.",
         "focus": "How does a community organise itself to care for a stranger in need?"},
    ],
    "events": [
        "A spice cart tips over and turns the square gold",
        "A travelling magician sets up by the fountain",
        "The bell tower rings thirteen times at noon",
        "A rare songbird escapes into the market",
        "A sudden rainstorm sends everyone under the awnings",
        "Someone discovers an old coin worth a fortune",
        "A famous chef arrives looking for ingredients",
        "The whole market smells of fresh bread at dawn",
    ],
}
