_M = "nvidia/Nemotron-Mini-4B-Instruct"

WORLD = {
    "id": "riverside_campus",
    "name": "Riverside Campus",
    "theme": "school-town campus beside a river",
    "palette": {"bg": "#071018", "grass": "#214b36", "road": "#253044"},
    "board": {
        "cols": 24,
        "rows": 16,
        "ambient": 10,
        "roads": {"cols": [3, 18], "rows": [4, 11]},
        "plaza": [[10, 7], [11, 7], [12, 7], [10, 8], [11, 8], [12, 8]],
        "plaza_center": [11, 7.5],
        "buildings": [
            {"gx": 6,  "gy": 1,  "w": 4, "d": 2, "h": 38, "kind": "block", "wall": "#7a7257", "roof": "#ffd76a", "label": "SCHOOL"},
            {"gx": 12, "gy": 1,  "w": 3, "d": 2, "h": 32, "kind": "block", "wall": "#5e7779", "roof": "#38e8ff", "label": "SCIENCE"},
            {"gx": 20, "gy": 1,  "w": 2, "d": 2, "h": 26, "kind": "house", "wall": "#9b8663", "roof": "#7a4a2e", "label": "GROUNDS"},
            {"gx": 5,  "gy": 6,  "w": 2, "d": 2, "h": 28, "kind": "shop",  "wall": "#8a6b50", "roof": "#ff8a5f", "label": "RIVER CAFÉ"},
            {"gx": 16, "gy": 6,  "w": 2, "d": 2, "h": 30, "kind": "block", "wall": "#5a8a7d", "roof": "#7CFFB2", "label": "NURSE"},
            {"gx": 8,  "gy": 13, "w": 3, "d": 2, "h": 24, "kind": "house", "wall": "#8a789b", "roof": "#9b6bff", "label": "DORMS"},
            {"gx": 14, "gy": 13, "w": 3, "d": 2, "h": 24, "kind": "house", "wall": "#7f9a72", "roof": "#4a6b32", "label": "FAMILY HALL"},
        ],
        "trees": [[2, 2], [4, 2], [5, 10], [8, 9], [13, 10], [16, 10], [20, 9], [21, 13], [6, 14], [2, 13]],
        "props": [
            {"type": "pond", "gx": 21, "gy": 5, "w": 2, "d": 6},
            {"type": "fountain", "gx": 11, "gy": 8},
            {"type": "bench", "gx": 9, "gy": 7},
            {"type": "bench", "gx": 13, "gy": 8},
            {"type": "table", "gx": 7, "gy": 8},
            {"type": "table", "gx": 5, "gy": 9},
            {"type": "lamp", "gx": 10, "gy": 6},
            {"type": "lamp", "gx": 14, "gy": 6},
            {"type": "planter", "gx": 12, "gy": 10},
        ],
        "hotspots_tile": {
            "school": [8, 3],
            "science_lab": [13, 3],
            "grounds_shed": [20, 3],
            "cafe": [6, 8],
            "nurse_office": [16, 8],
            "quad": [11, 7],
            "library_steps": [12, 10],
            "riverside_walk": [20, 11],
            "dorms": [9, 12],
            "family_hall": [15, 12],
            "square": [9, 8],
            "park": [14, 10],
        },
        "activities": {
            "Elena Brooks": {"tile": [8, 3], "label": "teaches in the classroom"},
            "Samir Patel": {"tile": [13, 3], "label": "checks the science lab"},
            "Maya Chen": {"tile": [11, 7], "label": "sketches on the quad"},
            "Rosa Alvarez": {"tile": [6, 8], "label": "runs the café counter"},
            "Talia Reed": {"tile": [16, 8], "label": "keeps the nurse office ready"},
            "Owen Moss": {"tile": [20, 11], "label": "walks the riverside grounds"},
        },
    },
    "cast": [
        {
            "name": "Elena Brooks", "age": 39, "job": "history teacher", "role": "worker",
            "traits": ["patient", "principled", "quietly funny"],
            "backstory": "She grew up nearby and came back to teach because the campus gave her a future.",
            "relationships": {"Samir Patel": "mentor", "Maya Chen": "mentor", "Rosa Alvarez": "friend", "Talia Reed": "friend", "Owen Moss": "ally"},
            "voice_description": "(a calm adult woman, clear warm teacherly voice)", "model": _M,
            "emoji": "👩‍🏫", "home": "school", "catchphrase_hint": "turns trouble into a lesson",
            "schedule": [[7, 8, "cafe", "coffee before homeroom", {"hunger": -8, "energy": 2}], [8, 15, "school", "teaching classes", {"energy": -10, "social": 8}], [15, 17, "library_steps", "grading on the steps", {"energy": -3}], [17, 22, "family_hall", "calling families and planning", {"energy": -4, "social": 2}], [22, 7, "family_hall", "resting", {"energy": 25}]],
        },
        {
            "name": "Samir Patel", "age": 16, "job": "science student", "role": "student",
            "traits": ["analytical", "anxious", "earnest"],
            "backstory": "He tracks campus patterns in spreadsheets and worries whenever the data gets weird.",
            "relationships": {"Elena Brooks": "mentor", "Maya Chen": "friend", "Rosa Alvarez": "friend", "Talia Reed": "trusts", "Owen Moss": "curious-about"},
            "voice_description": "(a thoughtful teenage boy, precise quick voice)", "model": _M,
            "emoji": "🧑‍🔬", "home": "dorms", "catchphrase_hint": "wants evidence before deciding",
            "schedule": [[7, 8, "dorms", "getting ready", {"energy": -2}], [8, 15, "science_lab", "classes and lab work", {"energy": -8, "social": 5}], [15, 17, "cafe", "study snack", {"hunger": -10, "social": 5}], [17, 22, "dorms", "homework", {"energy": -4}], [22, 7, "dorms", "sleeping", {"energy": 28}]],
        },
        {
            "name": "Maya Chen", "age": 15, "job": "art student", "role": "student",
            "traits": ["creative", "bold", "empathetic"],
            "backstory": "She sketches everyone on campus and notices feelings before facts.",
            "relationships": {"Elena Brooks": "mentor", "Samir Patel": "friend", "Rosa Alvarez": "family-friend", "Talia Reed": "trusts", "Owen Moss": "friend"},
            "voice_description": "(an expressive teenage girl, bright confident voice)", "model": _M,
            "emoji": "🎨", "home": "dorms", "catchphrase_hint": "describes events like scenes in a mural",
            "schedule": [[7, 8, "quad", "morning sketching", {"energy": -1}], [8, 15, "school", "classes", {"energy": -8, "social": 6}], [15, 18, "quad", "art club on the grass", {"energy": -4, "social": 8}], [18, 22, "dorms", "finishing projects", {"energy": -4}], [22, 7, "dorms", "sleeping", {"energy": 28}]],
        },
        {
            "name": "Rosa Alvarez", "age": 51, "job": "campus café owner", "role": "shopkeeper",
            "traits": ["generous", "sharp", "protective"],
            "backstory": "Her café is where students hear news, borrow courage, and sometimes get fed for free.",
            "relationships": {"Elena Brooks": "friend", "Samir Patel": "friend", "Maya Chen": "family-friend", "Talia Reed": "friend", "Owen Moss": "rival"},
            "voice_description": "(a lively middle-aged woman, rich amused voice)", "model": _M,
            "emoji": "☕", "home": "cafe", "catchphrase_hint": "connects every problem to feeding people",
            "schedule": [[6, 8, "cafe", "opening the café", {"energy": -3}], [8, 16, "cafe", "serving students", {"energy": -9, "social": 10}], [16, 18, "quad", "checking on regulars", {"social": 5}], [18, 22, "cafe", "closing and prep", {"energy": -4}], [22, 6, "cafe", "resting upstairs", {"energy": 24}]],
        },
        {
            "name": "Talia Reed", "age": 34, "job": "school nurse", "role": "medic",
            "traits": ["steady", "direct", "kind"],
            "backstory": "She knows which kids are actually sick and which ones just need someone to listen.",
            "relationships": {"Elena Brooks": "friend", "Samir Patel": "trusts", "Maya Chen": "trusts", "Rosa Alvarez": "friend", "Owen Moss": "ally"},
            "voice_description": "(a steady adult woman, gentle firm voice)", "model": _M,
            "emoji": "🩺", "home": "nurse_office", "catchphrase_hint": "triages feelings and injuries together",
            "schedule": [[7, 8, "cafe", "tea before clinic hours", {"hunger": -6}], [8, 16, "nurse_office", "nurse office hours", {"energy": -10, "social": 6}], [16, 18, "riverside_walk", "walking off the day", {"energy": -2}], [18, 22, "family_hall", "checking messages", {"social": 2}], [22, 7, "nurse_office", "resting on call", {"energy": 24}]],
        },
        {
            "name": "Owen Moss", "age": 58, "job": "groundskeeper", "role": "worker",
            "traits": ["patient", "superstitious", "observant"],
            "backstory": "He has maintained the campus paths for decades and knows every pipe, root, and rumor.",
            "relationships": {"Elena Brooks": "ally", "Samir Patel": "curious-about", "Maya Chen": "friend", "Rosa Alvarez": "rival", "Talia Reed": "ally"},
            "voice_description": "(an older man, low slow outdoorsy voice)", "model": _M,
            "emoji": "🧑‍🌾", "home": "grounds_shed", "catchphrase_hint": "blames the river, the weather, or old pipes first",
            "schedule": [[6, 8, "grounds_shed", "tool check", {"energy": -2}], [8, 12, "riverside_walk", "grounds rounds", {"energy": -8}], [12, 13, "cafe", "lunch at the counter", {"hunger": -10, "social": 4}], [13, 17, "quad", "repairs around the quad", {"energy": -7}], [17, 21, "grounds_shed", "locking up", {"energy": -3}], [21, 6, "grounds_shed", "sleeping", {"energy": 26}]],
        },
    ],
    "scenarios": [
        {"id": "exam_postponed", "title": "Final exams are postponed", "event": "The principal announces final exams are postponed because the riverside road flooded overnight.", "focus": "How do students and adults react differently when a stressful deadline suddenly moves?"},
        {"id": "cafe_closure", "title": "The café may lose its lease", "event": "A notice appears saying the campus café lease may not be renewed next semester.", "focus": "Why do shared places matter more than their official purpose?"},
        {"id": "nurse_overflow", "title": "The nurse office fills up", "event": "Half the school comes to the nurse after a mysterious rash starts spreading during lunch.", "focus": "How does a community balance urgency, fear and practical care?"},
    ],
    "events": [
        "The riverside path floods just before morning classes",
        "A rumor spreads that the old gym is haunted",
        "Someone paints a huge mural on the cafeteria wall overnight",
        "The school bell starts ringing five minutes early every hour",
        "A lost dog runs across the quad during lunch",
        "The science lab windows glow blue after sunset",
        "The café runs out of food during a surprise assembly",
        "A teacher finds an anonymous protest flyer in every locker",
    ],
}
