_M = "nvidia/Nemotron-Mini-4B-Instruct"

_TREES = [[7, 8], [12, 8], [7, 11], [12, 11], [8, 7], [11, 12], [6, 10], [13, 9],
          [3, 4], [17, 4], [3, 12], [18, 12], [6, 17], [13, 6], [18, 18], [2, 19]]

WORLD = {
    "id": "starhaven",
    "name": "Starhaven Station",
    "theme": "orbital colony in deep space",
    "palette": {"bg": "#070a16", "grass": "#15324a", "road": "#1e2740"},
    "board": {
        "cols": 20, "rows": 20,
        "roads": {"cols": [5, 14], "rows": [5, 14]},
        "plaza": [[9, 9], [10, 9], [9, 10], [10, 10]],
        "plaza_center": [9.5, 9.5],
        "buildings": [
            {"gx": 1,  "gy": 1,  "w": 2, "d": 2, "h": 70,  "kind": "dome",  "wall": "#3a4f6e", "roof": "#38e8ff", "label": "HABITAT"},
            {"gx": 8,  "gy": 1,  "w": 4, "d": 2, "h": 58,  "kind": "block", "wall": "#414a78", "roof": "#9b6bff", "label": "COMMS"},
            {"gx": 16, "gy": 1,  "w": 2, "d": 2, "h": 132, "kind": "tower", "wall": "#48527e", "roof": "#ff5fa2", "label": "COMMAND"},
            {"gx": 1,  "gy": 8,  "w": 2, "d": 3, "h": 66,  "kind": "dome",  "wall": "#2f5a52", "roof": "#7CFFB2", "label": "HYDROPONICS"},
            {"gx": 16, "gy": 7,  "w": 2, "d": 3, "h": 62,  "kind": "glass", "wall": "#5a5230", "roof": "#ffd76a", "label": "TRADE HUB"},
            {"gx": 1,  "gy": 16, "w": 3, "d": 2, "h": 60,  "kind": "block", "wall": "#6e4a30", "roof": "#ff8a5f", "label": "DOCK BAY"},
            {"gx": 8,  "gy": 16, "w": 4, "d": 2, "h": 64,  "kind": "dome",  "wall": "#3a4f6e", "roof": "#38e8ff", "label": "ARCHIVE"},
            {"gx": 16, "gy": 16, "w": 2, "d": 2, "h": 120, "kind": "tower", "wall": "#2f5a52", "roof": "#7CFFB2", "label": "REACTOR"},
        ],
        "trees": _TREES,
        "props": [
            {"type": "fountain", "gx": 9.5, "gy": 9.5},
            {"type": "pond", "gx": 11, "gy": 7, "w": 2, "d": 2},
            {"type": "lamp", "gx": 5, "gy": 9},
            {"type": "lamp", "gx": 14, "gy": 10},
            {"type": "bench", "gx": 7, "gy": 10},
            {"type": "patio", "gx": 15, "gy": 9},
        ],
        "hotspots_tile": {
            "habitat": [3, 2], "comms": [9, 3], "command": [16, 3], "hydro": [3, 9],
            "trade": [15, 8], "dock": [4, 16], "archive": [12, 16], "reactor": [9, 11],
            "park": [8, 9], "square": [10, 11],
        },
        "activities": {
            "Captain Vega": {"tile": [16, 3], "label": "🛰️ to the command deck"},
            "Rin Tanaka":   {"tile": [3, 9],  "label": "🌱 checks the hydroponics"},
            "Dex Okonkwo":  {"tile": [4, 16], "label": "🔧 to the docking bay", "vehicle": "bike"},
            "Ada-7":        {"tile": [9, 11], "label": "🤖 scans the reactor core"},
            "Mira Sol":     {"tile": [9, 3],  "label": "📡 broadcasts the news"},
        },
    },
    "cast": [
        {"name": "Captain Vega", "age": 52, "job": "station commander",
         "traits": ["stern", "strategic", "secretly weary"],
         "backstory": "Twenty years keeping Starhaven alive; trusts procedure over feelings, but the crew is the only family left.",
         "relationships": {"Rin Tanaka": "friend", "Dex Okonkwo": "ally", "Ada-7": "depends on", "Mira Sol": "mentor"},
         "voice_description": "(a commanding older woman, steady authoritative low voice)", "model": _M,
         "emoji": "🧑‍✈️", "home": "command", "catchphrase_hint": "frames everything as a risk to manage"},
        {"name": "Rin Tanaka", "age": 29, "job": "hydroponics botanist",
         "traits": ["gentle", "optimistic", "stubborn"],
         "backstory": "Grows the only fresh food on the station and believes living things fix most problems.",
         "relationships": {"Captain Vega": "friend", "Dex Okonkwo": "crush", "Ada-7": "friend", "Mira Sol": "older-sibling"},
         "voice_description": "(a warm young woman, soft hopeful mid voice)", "model": _M,
         "emoji": "👩‍🌾", "home": "hydro", "catchphrase_hint": "relates events to growth and patience"},
        {"name": "Dex Okonkwo", "age": 38, "job": "dock mechanic",
         "traits": ["gruff", "loyal", "improvises"],
         "backstory": "Can fix anything with scrap and swearing; pretends he doesn't care, cares the most.",
         "relationships": {"Captain Vega": "respect", "Rin Tanaka": "crush", "Ada-7": "rival", "Mira Sol": "friend"},
         "voice_description": "(a gruff adult man, gravelly blunt voice)", "model": _M,
         "emoji": "🧑‍🔧", "home": "dock", "catchphrase_hint": "immediately thinks about what will break"},
        {"name": "Ada-7", "age": 6, "job": "android caretaker",
         "traits": ["curious", "literal", "quietly caring"],
         "backstory": "An aging service android learning what feelings are by watching the crew; takes everything at face value.",
         "relationships": {"Captain Vega": "obeys", "Rin Tanaka": "friend", "Dex Okonkwo": "rival", "Mira Sol": "fascinated-by"},
         "voice_description": "(a calm synthetic voice, gently robotic and precise)", "model": _M,
         "emoji": "🤖", "home": "habitat", "catchphrase_hint": "interprets events very literally, then surprises everyone"},
        {"name": "Mira Sol", "age": 17, "job": "comms intern",
         "traits": ["dramatic", "plugged-in", "brave"],
         "backstory": "Born on the station; runs the unofficial broadcast and treats every event like breaking galactic news.",
         "relationships": {"Captain Vega": "looks-up-to", "Rin Tanaka": "younger-sibling", "Dex Okonkwo": "friend", "Ada-7": "fascinated-by"},
         "voice_description": "(an excitable teenager, fast bright voice)", "model": _M,
         "emoji": "🧑‍🚀", "home": "comms", "catchphrase_hint": "announces everything like a headline"},
    ],
    "scenarios": [
        {"id": "oxygen_drop", "title": "Life-support oxygen is dropping",
         "event": "Starhaven's life-support reports oxygen levels falling 2% per hour with no known cause.",
         "focus": "How do people prioritise when a shared resource everyone depends on is failing?"},
        {"id": "first_contact", "title": "An unknown ship is approaching",
         "event": "Long-range sensors pick up an unidentified ship on a slow approach to the station. It isn't answering hails.",
         "focus": "How do fear, curiosity and duty pull people in different directions?"},
        {"id": "supply_late", "title": "The supply shuttle is three weeks late",
         "event": "The quarterly supply shuttle from Earth is now three weeks overdue with no explanation.",
         "focus": "How do communities ration, cope and keep morale when help is delayed?"},
    ],
    "events": [
        "A meteor shower lights up the station's viewports",
        "The artificial gravity flickers for ten seconds",
        "A rare plant in hydroponics blooms for the first time",
        "An old distress signal starts replaying on every channel",
        "The station AI tells a joke for the first time ever",
        "A power surge knocks out the lights in the trade hub",
        "A stowaway cat is found in the docking bay",
        "The reactor hums at a strange new frequency",
    ],
}
